### ISSUE TITLE
BAD readme

### ISSUE THREAD

**Issue by lasote** [danimtb/sonoff-danimtb#24]
Improve readme:

a) Link to how to connect https://github.com/arendst/Sonoff-Tasmota/wiki/Hardware-Preparation
b) indicate the need (and command) of the submodule 
c) Explain wtf is the flash mode: press button (or gpi0 to gnd) and then plugin your usb

😠 LoL

**Comment by danimtb** [comment]
Readme has improved a lot and now indicates the supported devices with the needed wiring to be flashed. Flash mode is easier to understand now you have the wiring scheme.

**Comment by danimtb** [comment]
Released in 1.3.0
