### ISSUE TITLE
Long Press works for turn-on but not turn-off

### ISSUE THREAD

**Issue by lasote** [danimtb/sonoff-danimtb#29]
If I configure the switch channel of a different light as a secondary mqtt action, it works to turn-on the light, but it is not working to turn-off.
Tried with classic sonoff and with ewelink touch wall.
Any idea?

**Comment by danimtb** [comment]
My sonoff are working dine with that. That's the purpose of the long press secondary mqtt topic. However I have not tested it with the latest changes.

Will try to make some tests and let you know

**Comment by danimtb** [comment]
Turned out copy of relay object was not done completely. I switched it to use a pointer, which will be better for memory efficiency too.

**Comment by danimtb** [comment]
Released in 1.3.0
